title: Ideation
owner: Eric Silva
email: eric.jrsilva@gmail.com
description: My personal ideas
baseurl: "/minimalist" # the subpath of your site, e.g. /blog
url: "https://ericjrsilva.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username: ericjrsilva
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
